remote_theme : adueck/good-clean-read

# Site settings
title: My blog
tag_text: My blog
description: Nothin special, just my blog
url: "https://cntmin81.github.io"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
